name: IPL
main: de.mc_zone.ipl.IPL
version: 1.3.1
dev-url: http://dev.bukkit.org/server-mods/iplock-lock-your-account-dynamic/
description: This plugin allows you to require everyone or just selected players to match one of the IP's or hosts listed under their name in this plugin.
author: volpi3000
main: de.mc_zone.ipl.IPL
commands:
   ipl:
      description: Basic Command
      usage: /<command> [option] [args]
      permission: ipl.basic
      permisison-message: You don't have ipl.basic
   
